New platform: AIO-3588q
edk2-porting/edk2-rk3588 pull request #130
Opened 2024-03-23 23:55 UTC by idigdoug

Verified working in Windows:

- Serial Debug
- eMMC
- Pipe0 PCIe
- Pipe0 SATA
- PCIeX4
- USBC (XHC0)
- USB3 (XHC1)
- Ethernet 1
- Ethernet 2
- HDMI out
- RTC

Shows up in Windows but no driver (expected):

- HISI0031 UAR2
- OHC0
- OHC1
- PINC
- SDHC
- AMZN0001 PCI0.RES0
- AMZN0001 PCI4.RES0

Broken:

- ES8323: Windows device manager says it's ok but no sound comes through.

Yet to be tested:

- Linux ACPI
- Linux DeviceTree
- BSD ACPI
- BSD DeviceTree
- USB2 (adapter ordered)
- Pipe1 (Mini-PCIe, adapter ordered)
- Pipe2 (M.2-B key, adapter ordered)

2024-03-24 06:28 UTC, mariobalanica requested changes
Some reviews below, but LGTM otherwise.

2024-03-24 06:28 UTC, mariobalanica commented on edk2-rockchip/Platform/Firefly/AIO-3588Q/AIO-3588Q.dsc.inc
> +  gRK3588TokenSpaceGuid.PcdUsbDpPhy1Supported|TRUE
What about PHY 0? Firefly DT suggests it's enabled for Type-C (USB3 & DP).

2024-03-24 06:28 UTC, mariobalanica commented on edk2-rockchip/Platform/Firefly/AIO-3588Q/AIO-3588Q.dsc.inc
> +  gRK3588TokenSpaceGuid.PcdComboPhy2ModeDefault|$(COMBO_PHY_MODE_PCIE)
DT says this is connected to USB 3 Host.

2024-03-24 06:28 UTC, mariobalanica commented on edk2-rockchip/Platform/Firefly/AIO-3588Q/AcpiTables/Dsdt.asl
> +    // include ("Usb3Host2.asl")
Can be enabled once combo PHY 2 is routed to USB3.

2024-03-24 06:28 UTC, mariobalanica commented on edk2-rockchip/Platform/Firefly/AIO-3588Q/Library/RockchipPlatformLib/RockchipPlatformLib.c
> +  }
pcie2x1l0 and pcie2x1l2 should also have PERST defined here.

pcie2x1l2 uses `&pca9555 PCA_IO1_6 GPIO_ACTIVE_HIGH`. 
PCIe init code runs earlier than the I2C driver binding, so I suggest cloning RockchipPlatformLib.inf into RockchipPlatformLibPcaDepex.inf and adding this at the bottom:

```
[Depex]
  gPca95xxProtocolGuid
```

Then, add:
```
MdeModulePkg/Bus/Pci/PciHostBridgeDxe/PciHostBridgeDxe.inf {
    <LibraryClasses>
      RockchipPlatformLib|Platform/Firefly/AIO-3588Q/Library/RockchipPlatformLib/RockchipPlatformLibPcaDepex.inf
  }
```

to `AIO-3588-Q.dsc.inc` under `[Components.common]`.

It's not ideal but I can't think of a better way right now, since PciHostBridgeDxe does not follow the driver model..

2024-03-26 04:48 UTC, idigdoug commented on edk2-rockchip/Platform/Firefly/AIO-3588Q/AIO-3588Q.dsc.inc
> +  gRK3588TokenSpaceGuid.PcdUsbDpPhy1Supported|TRUE
Not sure what I was thinking. I guess I noticed that one XHCI is connected to an on-board hub, and the other is connected to a type-C port, and got mixed up on which one was which. Looks like XHC0 is the type-C port, and XHC1 is connected to the hub. So I guess this should be Phy0Supported = TRUE, Phy1Supported = FALSE?

Where do I get the PcdDp1LaneMux values?

2024-03-26 04:58 UTC, idigdoug commented on edk2-rockchip/Platform/Firefly/AIO-3588Q/AIO-3588Q.dsc.inc
> +  gRK3588TokenSpaceGuid.PcdComboPhy2ModeDefault|$(COMBO_PHY_MODE_PCIE)
PDF with the pin connection list listed the pin as "pcie/sata/usb3" and listed the "function for mainboard" as "pci3/sata", seemed to explicitly omit the usb3. I'm not sure I would consider it accessible, and I'm not sure it's particularly useful, not worth loading a driver for, so I left it off.

Sure, it's there in the DT, and I guess we can turn it on, but I'm not sure it really has any purpose.

2024-03-26 05:53 UTC, idigdoug commented on edk2-rockchip/Platform/Firefly/AIO-3588Q/Library/RockchipPlatformLib/RockchipPlatformLib.c
> +  }
I can see reset-gpios for pcie3x4 and pcie2x1l0, but I don't see them for the other ones.

My DT says pca9555 output 6 is `vcc_hub3_reset`.

2024-03-26 07:40 UTC, mariobalanica commented on edk2-rockchip/Platform/Firefly/AIO-3588Q/AIO-3588Q.dsc.inc
> +  gRK3588TokenSpaceGuid.PcdComboPhy2ModeDefault|$(COMBO_PHY_MODE_PCIE)
https://gitlab.com/firefly-linux/kernel/-/blob/rk3588/firefly/arch/arm64/boot/dts/rockchip/rk3588-firefly-aio-3588q.dtsi?ref_type=heads#L408

`usbhost_dwc3_0` is enabled here and will switch the `combphy2_psu` over to USB3.

2024-03-26 07:57 UTC, mariobalanica commented on edk2-rockchip/Platform/Firefly/AIO-3588Q/AIO-3588Q.dsc.inc
> +  gRK3588TokenSpaceGuid.PcdUsbDpPhy1Supported|TRUE
PHY 1 is also enabled here: https://gitlab.com/firefly-linux/kernel/-/blob/rk3588/firefly/arch/arm64/boot/dts/rockchip/rk3588-diff.dtsi#L236 (included by `rk3588-firefly-aio-3588q.dtsi`)

PHY 0 is the Type-C port, PHY1 is connected to both a DP->VGA converter and an USB3 port (?).

Lane mux for both PHYs should be `{ 0x2, 0x3 }`, this is hardcoded to one orientation and allows using both DP and USB3.

2024-03-26 08:11 UTC, mariobalanica commented on edk2-rockchip/Platform/Firefly/AIO-3588Q/Library/RockchipPlatformLib/RockchipPlatformLib.c
> +  }
This is the reset for pcie2x1l2: https://gitlab.com/firefly-linux/kernel/-/blob/rk3588/firefly/arch/arm64/boot/dts/rockchip/rk3588-firefly-aio-3588q.dtsi?ref_type=heads#L267

> My DT says pca9555 output 6 is vcc_hub3_reset.

`vcc_hub3_reset` is on bank 0, while pcie2x1l2 perst is on bank 1. This corresponds to pin `14`, since banks are divided into 8 pins.

2024-03-26 18:33 UTC, idigdoug commented on edk2-rockchip/Platform/Firefly/AIO-3588Q/Library/RockchipPlatformLib/RockchipPlatformLib.c
> +  }
I see. I've been using preprocessed DTS and decompiled DTB so I've been missing the stuff that is ifdef'ed out.

2024-03-26 21:49 UTC, mariobalanica approved these changes

2024-03-26 21:50 UTC, merged