edk2-rockchip: add NanoPi R6S conf from Radxa 5A
edk2-porting/edk2-rk3588 pull request #25
Opened 2023-06-24 08:44 UTC by initdc

build preview: https://github.com/initdc/edk2-rk3588/actions/runs/5363381047

I generated the `Logo.bmp` by using Photoshop, fomart: Windows 24bit.
The Logo looks not right on real machine.

<img width="300px" src="https://assets-1.vercel.app/20230624_133732.jpg"><img width="300px" src="https://assets-1.vercel.app/20230624_160139.jpg">

I don't know how to fix the Logo color issuse, I committed a just work Logo with HUE +128 degrees.
Here still  has a issuse, A  tiny color bar right of the logo.

You can just cherry-pick the first commit if you know the right way to solve it. feel free to merge.

2023-06-24 09:48 UTC, MollySophia requested changes

2023-06-24 09:48 UTC, MollySophia commented on edk2-rockchip/Platform/FriendlyElec/NanoPi-R6S/Library/RockchipPlatformLib/RockchipPlatformLib.c
> +UsbPortPowerEnable (
Please check the schematics carefully and make sure the operations in this file(RockPlatformLib.c) are correct.

As far as I see, the power enabling pin for the single USB3 for NanoPi R6S is GPIO1_D2, which doesn't match any of these here, and this may be the reason why your USB3 doesn't work.

2023-06-24 09:48 UTC, MollySophia commented on edk2-rockchip/Platform/FriendlyElec/NanoPi-R6S/NanoPi-R6S.dsc
> +  gRK3588TokenSpaceGuid.PcdComboPhy2ModeDefault|$(COMBO_PHY_MODE_USB3)
Both of the MultiPHYs on NanoPi R6S are used for PCIe and routed to onboard ethernet cards. Thus here they should all be COMBO_PHY_MODE_PCIE and be not switchable.

2023-06-24 09:53 UTC, MollySophia commented on edk2-rockchip/Platform/FriendlyElec/NanoPi-R6S/Library/RockchipPlatformLib/RockchipPlatformLib.c
> +  if(Segment == PCIE_SEGMENT_PCIE20L2) {
You can change these GPIO definitions for PCIe buses according to the schematics too if you want.
It looks like having been copy-pasted from rock5a without any changes.

2023-06-24 09:55 UTC, MollySophia commented
For the "Clock at 0.81 GHz" issue, you may check the settings in UiApp. The clock can be adjusted.

2023-06-24 13:18 UTC, mariobalanica commented
I can fix the logo if you send me the original one, but did we get permission from FriendlyELEC to use it here?

As for the clock issue, it should be checked in an OS.
The SMBIOS platform driver can happen to load earlier than the driver that sets the clocks, so it will report the boot default values. Can be ignored.

2023-06-24 13:20 UTC, initdc commented
> I can fix the logo if you send me the original one, but did we get permission from FriendlyELEC to use it here?
> 
> As for the clock issue, it should be checked in an OS. The SMBIOS platform driver can happen to load earlier than the driver that sets the clocks, so it will report the boot default values. Can be ignored.

I fetched from https://www.friendlyelec.com/image/catalog/logo.png

2023-06-24 13:26 UTC, mariobalanica commented on .github/workflows/single-build.yml
This is unrelated to the platform changes, and I'm still debating how to deal with these workflow runs so that we can keep release builds.

Should be removed and the platform added to build.yml for now.

2023-06-24 13:26 UTC, mariobalanica commented on edk2-rockchip/Platform/FriendlyElec/NanoPi-R6S/Library/RockchipPlatformLib/RockchipPlatformLib.c
> +UsbPortPowerEnable (
Same for the regulators, although all boards are pretty much identical in this regard, needs to be double checked so we don't end up frying anything.

Are the PCIe enable/resets correct? (do both Ethernet ports work?)

2023-06-24 22:34 UTC, mariobalanica commented
Everything okay with latest changes? Do USB and built-in Ethernet ports work now?

And what about the logo, are we allowed to use it?

2023-06-25 02:10 UTC, initdc commented
> Everything okay with latest changes? Do USB and built-in Ethernet ports work now?
> 
> And what about the logo, are we allowed to use it?

Nope. 
USB Both working, Win boot only when WTG driver pluging into USB3.0 directly. USB2.0 + Hub became not working on win OOBE. 
Using Radxa 5A conf, LAN1 wokring, with my conf, none of them were working...

ESXi just said you don't have a Eth adapter.

2023-06-25 15:02 UTC, mariobalanica commented
USB 2.0 not working is expected.

It's enough to test if the peripherals work in UEFI (`lspci`, `ifconfig -l`). ESXi does not have RTL8125 drivers.

2023-06-25 15:05 UTC, mariobalanica commented
Also, CI build failed because of platform name mismatch. Seems to be part of the NanoPi series rather than NanoPC.

2023-06-26 09:05 UTC, initdc commented
> USB 2.0 not working is expected.
> 
> It's enough to test if the peripherals work in UEFI (`lspci`, `ifconfig -l`). ESXi does not have RTL8125 drivers.

LAN1 working for now. WAN LAN2 not working.

2023-06-26 20:15 UTC, mariobalanica commented
This logo should be ok:
[Logo.zip](https://github.com/edk2-porting/edk2-rk3588/files/11873788/Logo.zip)

2023-06-30 19:14 UTC, mariobalanica approved these changes

2023-06-30 19:21 UTC, merged

2023-06-30 19:22 UTC, mariobalanica commented
Thanks for the contribution!